
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpas CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS friendship CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS films_directors CASCADE;
DROP TABLE IF EXISTS directors CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS reviews_likes CASCADE;
DROP TABLE IF EXISTS reviews_dislikes CASCADE;
DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS mpas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date date,
    duration integer,
    mpa_id INTEGER REFERENCES mpas (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar,
    email varchar,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    following_user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    followed_user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    status varchar,
    PRIMARY KEY (following_user_id, followed_user_id)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE
--     PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS directors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films_directors (
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    director_id INTEGER REFERENCES directors (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE NOT NULL,
    content varchar NOT NULL,
    is_positive bool NOT NULL,
    useful integer
);

CREATE TABLE IF NOT EXISTS reviews_likes (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    review_id INTEGER REFERENCES reviews (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews_dislikes (
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    review_id INTEGER REFERENCES reviews (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    entity_id integer,
    type varchar,
    operation varchar,
    timestamp long
);

DELETE FROM films;
DELETE FROM users;
DELETE FROM mpas;
DELETE FROM genres;
DELETE FROM friendship;
DELETE FROM likes;
DELETE FROM films_genres;
DELETE FROM directors;
DELETE FROM films_directors;
DELETE FROM reviews;
DELETE FROM reviews_likes;
DELETE FROM events;