
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date date,
    duration integer,
    genre_id INTEGER REFERENCES genres,
    rating_id INTEGER REFERENCES ratings
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar,
    email varchar,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    following_user_id INTEGER REFERENCES users,
    followed_user_id INTEGER REFERENCES users,
    status varchar
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER REFERENCES users,
    film_id INTEGER REFERENCES films
);

DELETE FROM films;
DELETE FROM users;
DELETE FROM ratings;
DELETE FROM genres;



