
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS mpas CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS mpas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date date,
    duration integer,
    mpa_id INTEGER REFERENCES mpas
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login varchar,
    email varchar,
    name varchar,
    birthday date
);

CREATE TABLE IF NOT EXISTS friendship (
    following_user_id INTEGER REFERENCES users,
    followed_user_id INTEGER REFERENCES users,
    status varchar
);

CREATE TABLE IF NOT EXISTS likes (
    user_id INTEGER REFERENCES users,
    film_id INTEGER REFERENCES films
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id INTEGER REFERENCES films,
    genre_id INTEGER REFERENCES genres
);

DELETE FROM films;
DELETE FROM users;
DELETE FROM mpas;
DELETE FROM genres;
DELETE FROM films_genres;
